services:
  Mooc.courses.CourseRepository:
    class: ../../../../Contexts/Mooc/Courses/infrastructure/FileCourseRepository
    arguments: []

  Mooc.courses.CreateCourse:
    class: ../../../../Contexts/Mooc/Courses/application/CreateCourse
    arguments: ["@Mooc.courses.CourseRepository"]

  Apps.mooc.controllers.CoursePutController:
    class: ../../controllers/CoursePutController
    arguments: ["@Mooc.courses.CreateCourse"]

  Apps.mooc.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []
