services:
  Mooc.courses.CourseRepository:
    class: ../../../../Mooc/Courses/infrastructure/FileCourseRepository
    arguments: []

  Mooc.courses.CreateCourse:
    class: ../../../../Mooc/Courses/application/CreateCourse
    arguments: ["@Mooc.courses.CourseRepository"]

  Mooc.shared.WinstonLogger:
    class: ../../../../Mooc/Shared/infrastructure/WinstonLogger
    arguments: []

  Apps.mooc.controllers.CreateCourseController:
    class: ../../controllers/CreateCourseController
    arguments: ["@Mooc.courses.CreateCourse"]

  Apps.mooc.controllers.StatusController:
    class: ../../controllers/StatusController
    arguments: []
