imports:
  - { resource: ./application.yaml }

services:
  Mooc.EnvironmentArranger:
    factory:
      class: ../../../../../tests/Contexts/Shared/infrastructure/arranger/EnvironmentArrangerFactory
      method: createEnvironmentArranger
    arguments: ["@Mooc.ConnectionManager"]
