services:
  Mooc.courses.CreateCourse:
    class: ../../../../Mooc/Courses/application/CreateCourse
    arguments: []

  Apps.mooc.controllers.CreateCourseController:
    class: ../../controllers/CreateCourseController
    arguments: ["@Mooc.courses.CreateCourse"]

  Apps.mooc.controllers.StatusController:
    class: ../../controllers/StatusController
    arguments: []
