services:
  Mooc.courses.CourseRepository:
    class: ../../../../Contexts/Mooc/Courses/infrastructure/FileCourseRepository
    arguments: []

  Mooc.courses.CourseCreator:
    class: ../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: ["@Mooc.courses.CourseRepository"]

  Apps.mooc.controllers.CoursePutController:
    class: ../../controllers/CoursePutController.CoursePutController
    arguments: ["@Mooc.courses.CourseCreator"]

  Apps.mooc.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []
