services:

  Apps.mooc.controllers.CoursePutController:
    class: ../../../controllers/CoursePutController
    arguments: ["@Mooc.shared.CommandBus"]

  Apps.mooc.controllers.StatusGetController:
    class: ../../../controllers/StatusGetController
    arguments: []

  Apps.mooc.controllers.CoursesCounterGetController:
    class: ../../../controllers/CoursesCounterGetController
    arguments: ["@Mooc.shared.QueryBus"]
