// TODO:
Instance CoursesCounterFinder application servicer

services:
  Contexts.shared.Logger:
    class: ../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Apps.Backoffice.Frontend.controllers.HomeGetController:
    class: ../../controllers/HomeGetController

  Apps.Backoffice.Frontend.controllers.CoursesGetController:
    class: ../../controllers/CoursesGetController
    arguments: ['@Mooc.coursesCounter.CoursesCounterFinder']
