services:
  Contexts.shared.Logger:
    class: ../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Apps.Backoffice.Frontend.controllers.HomeGetController:
    class: ../../controllers/HomeGetController

  Mooc.coursesCounter.CoursesCounterFinder:
    class: ../../../../../Contexts/Mooc/CoursesCounter/application/Find/CoursesCounterFinder
    arguments: ["@Mooc.coursesCounter.CoursesCounterRepository"]

  Mooc.coursesCounter.CoursesCounterRepository:
    class: ../../../../../Contexts/Mooc/CoursesCounter/infrastructure/persistence/mongo/MongoCoursesCounterRepository
    arguments: ["@Mooc.shared.ConnectionManager"]

  Mooc.shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['mooc']

  Mooc.courses.CourseRepository:
    class: ../../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@Mooc.shared.ConnectionManager']

  Mooc.shared.EventBus:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/InMemoryAsyncEventBus
    arguments: []

  Mooc.courses.CourseCreator:
    class: ../../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: ['@Mooc.courses.CourseRepository', '@Mooc.shared.EventBus']

  Apps.Backoffice.Frontend.controllers.CoursesGetController:
    class: ../../controllers/CoursesGetController
    arguments: ['@Mooc.coursesCounter.CoursesCounterFinder']

  Apps.Backoffice.Frontend.controllers.CoursesPostController:
    class: ../../controllers/CoursesPostController
    arguments: ['@Mooc.courses.CourseCreator']
